const zone = document.getElementById('zone');
const eventsEl = document.getElementById('events');
const scoreEl = document.getElementById('score');
const fpEl = document.getElementById('fp');
const logs = [];
const eventNames = [
  'pointerover','pointerenter','pointerdown','pointermove','pointerup','pointercancel','pointerout','pointerleave',
  'mouseover','mouseenter','mousedown','mousemove','mouseup','mouseout','mouseleave','click',
  'touchstart','touchmove','touchend','touchcancel'
];
function pick(e){return {type:e.type,t:Math.round(performance.now()*1000)/1000,x:e.clientX??null,y:e.clientY??null,pointerType:e.pointerType??null,isPrimary:e.isPrimary??null,buttons:e.buttons??null,button:e.button??null,pressure:e.pressure??null,width:e.width??null,height:e.height??null,isTrusted:e.isTrusted,touches:e.touches?e.touches.length:null};}
function update(){eventsEl.textContent=JSON.stringify(logs.slice(-80),null,2);scoreEl.textContent=JSON.stringify(scoreEvents(logs),null,2);}
function scoreEvents(items){const types=new Set(items.map(x=>x.type));const pointer=items.filter(x=>x.type.startsWith('pointer'));const mouse=items.filter(x=>x.type.startsWith('mouse')||x.type==='click');const touch=items.filter(x=>x.type.startsWith('touch'));const moves=items.filter(x=>x.type.includes('move'));const downs=items.filter(x=>x.type.includes('down')||x.type==='touchstart');const ups=items.filter(x=>x.type.includes('up')||x.type==='touchend');const untrusted=items.filter(x=>x.isTrusted===false).length;let score=100;if(items.length<8)score-=25;if(moves.length<3)score-=20;if(downs.length<1||ups.length<1)score-=20;if(pointer.length===0&&mouse.length===0&&touch.length===0)score-=20;if(untrusted>0)score-=30;if(types.has('pointerdown')&&!types.has('mousedown')&&touch.length===0)score-=8;if(types.has('mousedown')&&!types.has('pointerdown'))score-=8;const dts=[];for(let i=1;i<items.length;i++)dts.push(items[i].t-items[i-1].t);const avgDt=dts.length?dts.reduce((a,b)=>a+b,0)/dts.length:0;return{score:Math.max(0,Math.min(100,score)),verdict:score>=75?'event_chain_looks_complete_for_local_test':score>=45?'partial_or_needs_review':'incomplete_or_synthetic_signals',total:items.length,pointerEvents:pointer.length,mouseEvents:mouse.length,touchEvents:touch.length,moveEvents:moves.length,downEvents:downs.length,upEvents:ups.length,untrustedEvents:untrusted,avgIntervalMs:Math.round(avgDt*1000)/1000,eventTypes:Array.from(types)};}
for(const name of eventNames){zone.addEventListener(name,e=>{logs.push(pick(e));update();},{passive:true});}
document.getElementById('clear').onclick=()=>{logs.length=0;update();};
document.getElementById('export').onclick=()=>{const blob=new Blob([JSON.stringify({events:logs,score:scoreEvents(logs),fingerprint:fingerprint()},null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='event-diagnostics.json';a.click();URL.revokeObjectURL(a.href);};
function canvasHash(){try{const c=document.createElement('canvas');c.width=320;c.height=90;const ctx=c.getContext('2d');ctx.textBaseline='top';ctx.font='16px Arial';ctx.fillStyle='#f60';ctx.fillRect(0,0,320,90);ctx.fillStyle='#069';ctx.fillText('SliderTrajectoryLab 本地诊断 𝛑 😀',8,8);ctx.globalCompositeOperation='multiply';ctx.fillStyle='rgba(0,255,0,.35)';ctx.arc(80,55,35,0,Math.PI*2,true);ctx.fill();return c.toDataURL();}catch(e){return String(e)}}
function webglInfo(){try{const c=document.createElement('canvas');const gl=c.getContext('webgl')||c.getContext('experimental-webgl');if(!gl)return null;const dbg=gl.getExtension('WEBGL_debug_renderer_info');return{vendor:dbg?gl.getParameter(dbg.UNMASKED_VENDOR_WEBGL):gl.getParameter(gl.VENDOR),renderer:dbg?gl.getParameter(dbg.UNMASKED_RENDERER_WEBGL):gl.getParameter(gl.RENDERER),version:gl.getParameter(gl.VERSION),shadingLanguageVersion:gl.getParameter(gl.SHADING_LANGUAGE_VERSION),maxTextureSize:gl.getParameter(gl.MAX_TEXTURE_SIZE),maxViewportDims:gl.getParameter(gl.MAX_VIEWPORT_DIMS),extensions:gl.getSupportedExtensions()?.slice(0,60)}}catch(e){return{error:String(e)}}}
async function audioFingerprint(){try{const AC=window.OfflineAudioContext||window.webkitOfflineAudioContext;if(!AC)return null;const ctx=new AC(1,44100,44100);const osc=ctx.createOscillator();const comp=ctx.createDynamicsCompressor();osc.type='triangle';osc.frequency.value=10000;comp.threshold.value=-50;comp.knee.value=40;comp.ratio.value=12;comp.attack.value=0;comp.release.value=.25;osc.connect(comp);comp.connect(ctx.destination);osc.start(0);const buf=await ctx.startRendering();let sum=0;const data=buf.getChannelData(0);for(let i=0;i<data.length;i+=97)sum+=Math.abs(data[i]);return{sampleHash:Math.round(sum*1e8),length:data.length,sampleRate:buf.sampleRate};}catch(e){return{error:String(e)}}}
function detectFonts(){const base=['monospace','sans-serif','serif'];const test='mmmmmmmmmmlliWWWWW汉字😀';const size='72px';const canvas=document.createElement('canvas');const ctx=canvas.getContext('2d');const baseWidths={};for(const b of base){ctx.font=size+' '+b;baseWidths[b]=ctx.measureText(test).width;}const fonts=['Arial','Arial Black','Calibri','Cambria','Candara','Comic Sans MS','Consolas','Courier New','Georgia','Helvetica','Impact','Lucida Console','Microsoft YaHei','SimSun','NSimSun','Segoe UI','Tahoma','Times New Roman','Trebuchet MS','Verdana'];return fonts.filter(f=>base.some(b=>{ctx.font=size+` "${f}",`+b;return Math.abs(ctx.measureText(test).width-baseWidths[b])>.1;}));}
function clientHints(){const ua=navigator.userAgentData;if(!ua)return null;return{brands:ua.brands,mobile:ua.mobile,platform:ua.platform};}
async function fingerprintAsync(){const fp=fingerprint();fp.audio=await audioFingerprint();fpEl.textContent=JSON.stringify(fp,null,2);}
function fingerprint(){return{userAgent:navigator.userAgent,userAgentData:clientHints(),webdriver:navigator.webdriver,languages:navigator.languages,language:navigator.language,platform:navigator.platform,vendor:navigator.vendor,hardwareConcurrency:navigator.hardwareConcurrency,deviceMemory:navigator.deviceMemory,maxTouchPoints:navigator.maxTouchPoints,cookieEnabled:navigator.cookieEnabled,doNotTrack:navigator.doNotTrack,timezone:Intl.DateTimeFormat().resolvedOptions().timeZone,timezoneOffset:new Date().getTimezoneOffset(),screen:{w:screen.width,h:screen.height,aw:screen.availWidth,ah:screen.availHeight,colorDepth:screen.colorDepth,pixelDepth:screen.pixelDepth,devicePixelRatio:window.devicePixelRatio,innerWidth:innerWidth,innerHeight:innerHeight,outerWidth:outerWidth,outerHeight:outerHeight},plugins:Array.from(navigator.plugins||[]).map(p=>({name:p.name,filename:p.filename,description:p.description})).slice(0,30),mimeTypes:Array.from(navigator.mimeTypes||[]).map(m=>({type:m.type,suffixes:m.suffixes,description:m.description})).slice(0,30),permissionsApi:!!navigator.permissions,fontsDetected:detectFonts(),webgl:webglInfo(),canvasSamplePrefix:canvasHash().slice(0,120)+'...',notes:['TLS/HTTP2 fingerprint is server-side and cannot be fully read from browser JS. Use src/network_diagnostics.py for local TLS/ALPN observations.','IP reputation is network/provider context; this page does not bypass or modify it.']};}
fingerprintAsync();update();
